  # Google Sheets Configuration
  google_sheets_id = "1PlGPV2vAjz_gBOMykun9YSt6ccMxuX7vi5VYfuYgl8E"

  [google_sheets]
  type = "service_account"
  project_id = "ptw-timesheet-app"
  private_key_id = "0bcd3e8c5639c0b7ffb91ee36523eb624b9f6770"
  private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCjwih5XX/W2ds9\nJzlU7Q8hRF8H9TVtNDfNAbuylwxd/WpA8FICJEx/
  wsLS85lQ37gRylaySjY5QlGm\nxAQsuysNw1+ZcSqXtbM8WQ2+C+fSe9X9ZBToZHiJx7gLdOnafNU+QylGvUhKMs28\nr2Rxkb1XQYrv3fyU8oQFqaB+drVp2CrwckC66pqHMvpQmjdrqwFp/
  mB5Ea0EikaQ\n6QhCdpFlIMtKALYRWfpktgD3I+XPmfDOjcQU5PnSeNbbq97oCIBVDJqR7tX5FCVa\nsA3EetjyWcVcirKVKuM5ECgX2VGPsChOZI733prHXMF9AIEg7Hm14gnc8sflQmO3\n2/
  Jqw3dJAgMBAAECggEAAMqyKScQdIycXKL1SiG0zGWBG5/eBKOHXwqCerI0BTrR\n0hNPZDMCey4pBL3YiI1yXYSnz2ggM73sOOUS+5filQgULODhErd2UMUB9eCnG+uN\nHPLoTnjY49qnO0fzDwNCQTEwMIc/
  A5vUBpTnBI0OuC6pEjCVtW8oQAJCVEY06Zh3\n3Mywv3r3HOEVK8e3VR/7iIz/jBi8+Jv2AtRtrY4O9ytN/hwfTZtREpFlx3f07g6Y\nklvQPtalvNYPlFK9ZRdv59/ENXS/
  lI5W4t7O945ODk0W4F9MEEzFnyQVeTOZ976M\nnvRwtEEMGCJTeiOp2OkFfrX4iwCVQcOxq9tqZRZmYQKBgQDfzgw+ogy2EU6oBm+v\nG6unVVeXtyQzUn3wPqUwZ07NugYz3nj7bTH7+lTKBAsg7Z7+Q5zlX3xiREHYVI7u\nqQUBXUs+vhMfE6V1/vaBWay7xqaCZWN7TpDxOlBxGBg/
  Uhuk17rKjdWAHpGcIrrL\nYU1VyHieieMxGY+ckXdux4PSIQKBgQC7UM8yiJZRprZVBrKSIrP9P1fVtUaXaGIU\nCp0b1U8h6BVPfGcuSZNmOLf7+xYGAfjS3qZ1wyDUkH+SD7ECj1UYUP0tMbWDJbl2\nIbPSnHj+SMSWtskmB54mLKHutvvPNZakYbWn+ybQyv3ASxyekCnFH
  Zwceda59g0c\niwFx9mzQKQKBgQCZ/Wc1bUC7wXrSZ+NOpAZe03y6ehvhaEAZHrGAdYSmTvnXlJq/\nvKlozBytB0008eq03obE2Ad4gaiglcXm9srn3m5YlGYJuvXdE3o/
  FBmi9hM5o1No\n020tXcddmYuNfgxhRsJSfnbJeb8MpGTMbX3NqWs9AnkdHo5O11RLF+JeoQKBgHZL\n8Z7bbfuBCtOl2C68ZemBEIqx4jQKwy4fCdujGkeyl4rMaSltY/6BwYgMqXr/0dHy\ntTPYGKrF2xs2d7bDKJ2jwFDDfPunXnpBjJxtH2iQMj9wjpZK51D6jQYCYAMbt
  9h2\nsM+2qGviVuETTq7BIvAO5CGDvN1SjDNDgpUjaNMJAoGASEJj7JUkYaf/LZIMdmBq\nbALBuhxcGb7woRwmmpKz8p9v2SpXcviz/vyhK9BZBSV4EuE1R/
  R0zgNgXu3Je8+Z\nX6g0TU5ThcN+sU1Wv1w0OGjGnX9oyESI83xcEbzbdtveLvc6aFnakei6S1KFFPog\nVPxJLMGmJm7Ry78uX8mF3DA=\n-----END PRIVATE KEY-----\n"
  client_email = "ptw-timesheet-service@ptw-timesheet-app.iam.gserviceaccount.com"
  client_id = "105086036491360146942"
  auth_uri = "https://accounts.google.com/o/oauth2/auth"
  token_uri = "https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
  client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ptw-timesheet-service%40ptw-timesheet-app.iam.gserviceaccount.com"
  universe_domain = "googleapis.com"